name: Echo Changed Files

on:
  push:
    branches:
      - "**"
    paths:
      - "**"

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@315505acf41d2913b71af48080fb158cd01f79e7
        with:
          dir_names: true
          files: |
            **.tf
            **.hcl
            **.tfvars
            !*/*/*/bootstrap/**

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Expand List
        id: expand-list
        run: |
          INPUT_LIST=(${{ steps.changed-files.outputs.all_changed_files }})
          OUTPUT=""
          for path in "${INPUT_LIST[@]}"; do
            DEPTH=$(echo "$path" | awk -F'/' '{print NF}')
            SUBFOLDERS=$(find "$path" -type d -mindepth $((3 - DEPTH)) -maxdepth $((3 - DEPTH)))
            OUTPUT+=$(echo "$SUBFOLDERS" | sed 's|/|_|g')$'\n'
          done
          echo "folder_list=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Use the output in a subsequent step
        run: echo ${{ steps.expand-list.outputs.folder_list }}
