name: Echo Changed Files

on:
  push:
    branches:
      - "**"
    paths:
      - "**"
      - "!**/**/**/bootstrap/**"

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@315505acf41d2913b71af48080fb158cd01f79e7
        with:
          files: |
            *.tf
            *.hcl
            !**/**/**/botstrap/**

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
