name: Infra

on:
  workflow_dispatch:
    inputs:
      manual_path:
        description: 'Provided paths (comma-separated if multiple) without "/" at beggining.'
        required: false
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@6abeaa506a419f85fa9e681260b443adbeebb3d4
        with:
          dir_names: true
          files: |
            **.tf
            **.hcl
            **.tfvars
            !*/*/*/bootstrap/**

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Generate Matrix
        id: generate-matrix
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          MANUAL_PATHS="${{ github.event.inputs.manual_path }}"

          if [[ -n "$MANUAL_PATHS" ]]; then
            echo "Manual paths provided: $MANUAL_PATHS"
            CHANGED_FILES="${CHANGED_FILES}"$'\n'"${MANUAL_PATHS//,/\\n}"
          fi

          MATRIX_OUTPUT=$(CHANGED_FILES="$CHANGED_FILES" ./.github/scripts/generate_matrix.sh)
          echo $MATRIX_OUTPUT
          echo "matrix=$MATRIX_OUTPUT" >> "$GITHUB_OUTPUT"


  terraform:
    if: ${{ needs.matrix.outputs.matrix != '{"include":[]}' && needs.matrix.outputs.matrix != '' }}
    name: ${{ matrix.workspace }}/${{ matrix.region }}/${{ matrix.cluster }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    environment: ${{ matrix.workspace }}-${{ matrix.region }}-${{ matrix.cluster }}
    outputs:
      has_secret: ${{ steps.check-secret.outputs.has_secret }}
      workspace: ${{ matrix.workspace }}
      region: ${{ matrix.region }}
      cluster: ${{ matrix.cluster }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Env Secret Name to look for
        id: set-secret
        run: |
          ENV_NAME="${{ matrix.workspace }}-${{ matrix.region }}-${{ matrix.cluster }}"
          CLEANED_ENV=$(echo "$ENV_NAME" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
          SECRET_NAME="${CLEANED_ENV}_SECRET"
          echo "We look for: $SECRET_NAME"
          echo "secret_name=$SECRET_NAME" >> $GITHUB_OUTPUT

      - name: Check if Env secret exist
        id: check-secret
        env:
          SECRET_VALUE: ${{ secrets[steps.set-secret.outputs.secret_name] }}
          SECRET_NAME: ${{ steps.set-secret.outputs.secret_name }}
        run: |
          if [ -z "$SECRET_VALUE" ]; then
            echo "The secret $SECRET_NAME is empty or not set."
          else
            echo "The secret $SECRET_NAME is set."
            echo "has_secret=true" >> $GITHUB_OUTPUT
          fi

  bootstrap:
    name: Trigger Bootstrap Workflow
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ needs.terraform.outputs.has_secret == 'true' }}
    strategy:
      matrix:
        workspace: ${{ needs.terraform.outputs.workspace }}
        region: ${{ needs.terraform.outputs.region }}
        cluster: ${{ needs.terraform.outputs.cluster }}
    uses: gucio1200/renovate_sandbox/.github/workflows/bootstrap.yaml@main
    with:
      manual_path: "${{ matrix.workspace }}/${{ matrix.region }}/${{ matrix.cluster }}"
