name: Matrix

on:
  push:
    branches:
      - "**"
    paths:
      - "**"

concurrency:
  group: ${{ github.workflow }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
        with:
          dir_names: true
          files: |
            **.tf
            **.hcl
            **.tfvars
            !*/*/*/bootstrap/**

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Generate Matrix
        id: generate-matrix
        run: |
          DEPTH_LOOK=3
          INPUT_LIST=(${{ steps.changed-files.outputs.all_changed_files }})
          OUTPUT='{"include": []}'
          for path in "${INPUT_LIST[@]}"; do
            DEPTH=$(echo "$path" | awk -F'/' '{print NF}')
            SUBFOLDERS=$(find "$path" -type d -mindepth $((DEPTH_LOOK - DEPTH)) -maxdepth $((DEPTH_LOOK - DEPTH)))
            for folder in $SUBFOLDERS; do
              IFS='/' read -r workspace region cluster <<< "$folder"
              OUTPUT=$(echo "$OUTPUT" | jq --arg workspace "$workspace" --arg region "$region" --arg cluster "$cluster" \
              '.include += [{"workspace": $workspace, "region": $region, "cluster": $cluster}]')
            done
          done
          OUTPUT=$(echo "$OUTPUT" | jq -c '.include |= unique')
          echo $OUTPUT
          echo "matrix=$OUTPUT" >> $GITHUB_OUTPUT

  deploy:
    if: ${{ needs.matrix.outputs.matrix != '{"include":[]}' && needs.matrix.outputs.matrix != '' }}
    name: ${{ matrix.workspace }}-${{ matrix.region }}-${{ matrix.cluster }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    environment: ${{ matrix.workspace }}-${{ matrix.region }}-${{ matrix.cluster }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo ${{ matrix.workspace }}-${{ matrix.region }}-${{ matrix.cluster }}

#      - name: Force failure
#        run: exit 1
